import Head from "next/head";
import Main from "@/components/main";


export default function Home() {
  
  
  return (
    <div className="h-screen bg-blue-100 flex items-center justify-center">
      <Head>
        <title>QR code component</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon-32x32.png" />
      </Head>
      <Main />
    </div>
  );
}
